std_msgs/Header header
uint8 mode
# float64 w
# int64 timestamp
# bool is_controlled
float32 imu_pitch
float32 imu_yaw
bool is_target_lost
string vehicle_id
uint16 vehicle_hp
float64 spinning_period
float32 bullet_speed
float32 shoot_delay
bool is_clockwise
bool target_switched
bool is_spinning
bool spinning_switched
bool is_still_spinning
bool hit_7
geometry_msgs/Quaternion quat_imu
Armor[] armors
